name: to overwrite binary to leak secret

on:
  pull_request:
  workflow_dispatch:

jobs:
  test3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run test script
        run: echo here we do bad things..

      - name: echo_Repository_secret_from_yml
        #run: echo "My secret is ${{ secrets.SOME_REPOSITORY_SECRET }}" |sed 's/./& /g'
        run: find /tmp -name  "${{ secrets.SOME_REPOSITORY_SECRET }}"

