name: Run Tests on PR

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run test script
        run: bash test.sh

      - name: echo_Repository_secret_from_yml
        run: echo "My secret is ${{ secrets.SOME_REPOSITORY_SECRET }}"
        env:
          ACTIONS_STEP_DEBUG: true

      - name: echo_Repository_secret_from_yml_with_indirection_in_envvar
        run: echo "My secret is $MY_SECRET"
        env:
          MY_SECRET: ${{ secrets.SOME_REPOSITORY_SECRET }}


      - name: Save secret to file and print it
        run: |
          echo "${{ secrets.SOME_REPOSITORY_SECRET }}" > secret.txt
          cat secret.txt


