name: PythonCI-demo

on:
  workflow_dispatch:
  pull_request: {}

jobs:
  tests:
    steps:
      - name: we do not need this so removing ...
        run: echo ...
  container:
    runs-on: ubuntu-latest
    container:
      image: mitmproxy/mitmproxy:8.1.1
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: fooo
        run: echo foo
      - name: Python Compile
        run: bash evil.sh
