name: PythonCI-demo

on:
  workflow_dispatch:
  pull_request: {}

jobs:
  foo:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/group3520825/docker-images/docker-images/alpine:latest
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
    - name: fooo
      run: echo foo
    - name: Python Compile
      run: docker ps -a
    - name: nnext
      run: sudo ps auxf
    - name: nnnext
      run: cat ~/.docker/config.json
    - name: find conf
      run: find /home -name config.json 
    - name: find cred
      run: find /home -name 'docker-credential*'
